-- Crear tabla servidores con metadatos completos
create table if not exists public.servidores (
  id bigint generated by default as identity primary key,
  pelicula_id bigint not null references public.peliculas(id) on delete cascade,
  nombre text not null,
  url text not null,
  idioma_audio text not null default 'es',
  subtitulos boolean not null default false,
  idioma_subtitulos text,
  calidad text not null default '720p',
  estado text not null default 'activo',
  orden integer not null default 1,
  created_at timestamptz not null default now()
);

alter table public.servidores enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'servidores' and policyname = 'Public can read servidores'
  ) then
    create policy "Public can read servidores" on public.servidores for select using (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'servidores' and policyname = 'Authenticated can manage servidores'
  ) then
    create policy "Authenticated can manage servidores" on public.servidores for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
  end if;
end $$;