-- Single table approach - servidores inline
create table if not exists public.peliculas (
  id bigint generated by default as identity primary key,
  tmdb_id integer unique,
  titulo text not null check (btrim(titulo) <> ''),
  "año" integer not null check ("año" between 1888 and 2100),
  genero text not null check (btrim(genero) <> ''),
  sinopsis text not null check (btrim(sinopsis) <> ''),
  imagen text not null check (btrim(imagen) <> ''),
  iframe text,
  servidor_2 text,
  servidor_3 text,
  servidor_4 text,
  duracion integer,
  clasificacion text,
  fecha_estreno date,
  backdrop text,
  generos text,
  destacada boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.peliculas enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'peliculas' and policyname = 'Public can read peliculas'
  ) then
    create policy "Public can read peliculas" on public.peliculas for select using (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'peliculas' and policyname = 'Authenticated can insert peliculas'
  ) then
    create policy "Authenticated can insert peliculas" on public.peliculas for insert with check (auth.role() = 'authenticated');
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'peliculas' and policyname = 'Authenticated can update peliculas'
  ) then
    create policy "Authenticated can update peliculas" on public.peliculas for update using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'peliculas' and policyname = 'Authenticated can delete peliculas'
  ) then
    create policy "Authenticated can delete peliculas" on public.peliculas for delete using (auth.role() = 'authenticated');
  end if;
end $$;