-- UltraPelis / Supabase schema
-- Ejecuta esto en el SQL Editor de Supabase.
-- No necesitas API key para correr este script.
-- Para la app web solo debes usar la URL del proyecto y la anon key.

create extension if not exists pg_trgm;

create table if not exists public.peliculas (
  id bigint generated by default as identity primary key,
  titulo text not null check (btrim(titulo) <> ''),
  "año" integer not null check ("año" between 1888 and 2100),
  genero text not null check (btrim(genero) <> ''),
  sinopsis text not null check (btrim(sinopsis) <> ''),
  imagen text not null check (btrim(imagen) <> ''),
  iframe text not null check (btrim(iframe) <> ''),
  destacada boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists peliculas_created_at_idx on public.peliculas (created_at desc);
create index if not exists peliculas_genero_idx on public.peliculas (genero);
create index if not exists peliculas_titulo_trgm_idx on public.peliculas using gin (lower(titulo) gin_trgm_ops);

alter table public.peliculas enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'peliculas'
      and policyname = 'Public can read peliculas'
  ) then
    create policy "Public can read peliculas"
      on public.peliculas
      for select
      using (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'peliculas'
      and policyname = 'Authenticated can insert peliculas'
  ) then
    create policy "Authenticated can insert peliculas"
      on public.peliculas
      for insert
      with check (auth.role() = 'authenticated');
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'peliculas'
      and policyname = 'Authenticated can update peliculas'
  ) then
    create policy "Authenticated can update peliculas"
      on public.peliculas
      for update
      using (auth.role() = 'authenticated')
      with check (auth.role() = 'authenticated');
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'peliculas'
      and policyname = 'Authenticated can delete peliculas'
  ) then
    create policy "Authenticated can delete peliculas"
      on public.peliculas
      for delete
      using (auth.role() = 'authenticated');
  end if;
end $$;

do $$
begin
  if exists (
    select 1
    from pg_publication
    where pubname = 'supabase_realtime'
  ) and not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'peliculas'
  ) then
    alter publication supabase_realtime add table public.peliculas;
  end if;
end $$;
