-- UltraPelis / Supabase schema
-- Ejecuta esto en el SQL Editor de Supabase.
-- No necesitas API key para correr este script.
-- Para la app web solo debes usar la URL del proyecto y la anon key.

create extension if not exists pg_trgm;

create table if not exists public.peliculas (
  id bigint generated by default as identity primary key,
  tmdb_id integer unique,
  titulo text not null check (btrim(titulo) <> ''),
  "año" integer not null check ("año" between 1888 and 2100),
  genero text not null check (btrim(genero) <> ''),
  sinopsis text not null check (btrim(sinopsis) <> ''),
  imagen text not null check (btrim(imagen) <> ''),
  duracion integer,
  clasificacion text,
  fecha_estreno date,
  backdrop text,
  generos text,
  destacada boolean not null default false,
  created_at timestamptz not null default now()
);

-- Table for multiple servers per movie (normalized)
create table if not exists public.servidores (
  id bigint generated by default as identity primary key,
  pelicula_id bigint not null references public.peliculas(id) on delete cascade,
  nombre text not null check (btrim(nombre) <> ''),
  url text not null check (btrim(url) <> ''),
  idioma_audio text not null default 'es' check (idioma_audio in ('es', 'es-CO', 'en', 'ja', 'other')),
  subtitulos boolean not null default false,
  idioma_subtitulos text check (idioma_subtitulos in ('es', 'en', 'other')),
  calidad text not null default '720p' check (calidad in ('480p', '720p', '1080p', '4k')),
  estado text not null default 'activo' check (estado in ('activo', 'caido')),
  orden integer not null default 1,
  created_at timestamptz not null default now()
);

create index if not exists servidores_pelicula_idx on public.servidores (pelicula_id);
create index if not exists servidores_orden_idx on public.servidores (pelicula_id, orden);

-- Enable RLS on servidores table
alter table public.servidores enable row level security;

-- Policies for servidores table
do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'servidores'
      and policyname = 'Public can read servidores'
  ) then
    create policy "Public can read servidores"
      on public.servidores
      for select
      using (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'servidores'
      and policyname = 'Authenticated can manage servidores'
  ) then
    create policy "Authenticated can manage servidores"
      on public.servidores
      for all
      using (auth.role() = 'authenticated')
      with check (auth.role() = 'authenticated');
  end if;
end $$;

create index if not exists peliculas_created_at_idx on public.peliculas (created_at desc);
create index if not exists peliculas_genero_idx on public.peliculas (genero);
create index if not exists peliculas_titulo_trgm_idx on public.peliculas using gin (lower(titulo) gin_trgm_ops);

alter table public.peliculas enable row level security;

-- Make iframe and tmdb_id optional for existing data
alter table public.peliculas alter column iframe drop not null;
alter table public.peliculas alter column tmdb_id drop not null;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'peliculas'
      and policyname = 'Public can read peliculas'
  ) then
    create policy "Public can read peliculas"
      on public.peliculas
      for select
      using (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'peliculas'
      and policyname = 'Authenticated can insert peliculas'
  ) then
    create policy "Authenticated can insert peliculas"
      on public.peliculas
      for insert
      with check (auth.role() = 'authenticated');
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'peliculas'
      and policyname = 'Authenticated can update peliculas'
  ) then
    create policy "Authenticated can update peliculas"
      on public.peliculas
      for update
      using (auth.role() = 'authenticated')
      with check (auth.role() = 'authenticated');
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'peliculas'
      and policyname = 'Authenticated can delete peliculas'
  ) then
    create policy "Authenticated can delete peliculas"
      on public.peliculas
      for delete
      using (auth.role() = 'authenticated');
  end if;
end $$;

do $$
begin
  if exists (
    select 1
    from pg_publication
    where pubname = 'supabase_realtime'
  ) and not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'peliculas'
  ) then
    alter publication supabase_realtime add table public.peliculas;
  end if;
end $$;
